# Copyright 2019 The Grin Developers
# Modifications Copyright 2019 The Gotts Developers
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

dist: trusty
sudo: required
language: rust
rust:
- stable
git:
  depth: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - cmake
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev
    - cmake
    - gcc
    - binutils-dev

cache:
  cargo: true
  timeout: 240
  directories:
  - "$HOME/.cargo"
  - "$TRAVIS_BUILD_DIR/target"

env:
  global:
  - RUST_BACKTRACE="1"
  - RUSTFLAGS="-C debug-assertions"
  - VCPKGRS_DYNAMIC=1

matrix:
  include:
  - os: linux
    env: CI_JOB="test"        CI_JOB_ARGS="config libwallet api"
  - os: linux
    env: CI_JOB="test"        CI_JOB_ARGS="impls"
  - os: linux
    env: CI_JOB="test"        CI_JOB_ARGS="controller xyz"
  - os: linux
    env: CI_JOB="release"     CI_JOB_ARGS=
  - os: osx
    env: CI_JOB="test"        CI_JOB_ARGS="config libwallet api"
  - os: osx
    env: CI_JOB="test"        CI_JOB_ARGS="impls"
  - os: osx
    env: CI_JOB="test"        CI_JOB_ARGS="controller xyz"
  - os: osx
    env: CI_JOB="release"     CI_JOB_ARGS=
  - os: windows
    env: CI_JOB="test"        CI_JOB_ARGS="config"
  - os: windows
    env: CI_JOB="test"        CI_JOB_ARGS="libwallet"
# - os: windows
#   env: CI_JOB="test"        CI_JOB_ARGS="api"
  - os: windows
    env: CI_JOB="test"        CI_JOB_ARGS="impls"
  - os: windows
    env: CI_JOB="test"        CI_JOB_ARGS="controller"
  - os: windows
    env: CI_JOB="test"        CI_JOB_ARGS="xyz"
  - os: windows
    env: CI_JOB="release"     CI_JOB_ARGS=

script:
- bash .ci/general-jobs

before_cache:
- rm -rf $TRAVIS_BUILD_DIR/target/tmp
- rm -rf $TRAVIS_BUILD_DIR/target/test_output
- rm -rf $TRAVIS_BUILD_DIR/controller/test_output

before_deploy:
- bash .ci/release-jobs

deploy:
  provider: releases
  api_key:
    secure: iNscMlD/B9rcSeaPKazdwCdbdK3DJYGXS4TmjWiCro1ZQ5YkcMO/fvG9gN8uH4PijUBXvF9KwOlszu66U3MTx1gWfEfJs/9QrOQLJOwDzWTXXF8sfIbs51h6DyEF2MSC0Aij58ui6CfEkxWhTqzVfj/5KXl93Q2RZ7qB4x6bJwb8K7BEuTxwdVnWIav4vDmmhBjZ2/jrOnW59aPMnVnTne+wiUSFPaIrwv4u3LF9g3TB8wlaURX+IMi1UDQ/Izu9O4u27r/IOzDBJNDApA3NLYG++yhzLPmr1rN5xbJBB29xQ5hNyIaNXYk5Sj2XIyETXm4Jt98GksSIBxW4GC1GUlfbxq8SU+BqdOmzNj4dJ0yCakMgbPx1YKL+WiZTTWflUF+KaZ2nLKY6OarnrcaIjjXO9kADR4ZLF5YPeVYDrL5YI8sB3/luwdTT+vttZ1kg32VEJuuN43lpALUzwxJpqkSfEhi15UFbQYgBtP3I0lhploLkX9E19OIBN9I8hW3tqQv6FPLUuJ+yP0SQcLkOq57shG6/uwTC1hVtOtgomZZRdRt9gTugB2DSQPy1WB1KdOpWrrzSXGP0vd5Zf4nChubID8ZRLy3JuY5jdwZCuYhNL57ZrmeFaFbDL7bOGhv9+RM227JvKMqkHjA9tEIzfCQMwhuyP7kLXIQ6Shnynhs=
  file_glob: true
  file: target/release/gotts-wallet-*.*
  skip_cleanup: true
  on:
    repo: gottstech/gotts-wallet
    tags: true
